### ISSUE TITLE
How do I run this

### ISSUE THREAD

**Issue by wesgro2** [timothyswt/big-decks#1]
I have 0 exp with building and running projects.  Could you provide a walk through or point me in the right direction to learn?

**Comment by wesgro2** [comment]
I tried to install Babel and build it locally on my machine, but I am getting many errors.

**Comment by wesgro2** [comment]
D:\big-decks-master>npm run build

> big-decks@1.0.0 build D:\big-decks-master
> babel src -d lib


D:\big-decks-master\node_modules\babel-cli\node_modules\babel-core\node_modules\babel-code-frame\node_modules\chalk\node_modules\ansi-styles\index.js:2
const colorConvert = require('color-convert');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\big-decks-master\node_modules\babel-cli\node_modules\babel-core\node_modules\babel-code-frame\node_modules\chalk\index.js:3:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8
npm ERR! not ok code 0

**Comment by orneryd** [comment]
Hey there! 

you shouldn't have to run this yourself. all the decks are checked in. but if you do, all you should need to do is run
```
npm install && npm run start
```
you need to use node.js version 7.x+ as well.

**Comment by orneryd** [comment]
FYI I'm on node 7.8 and i just verified that a fresh clone of the repo running npm install followed by npm run start processes everything.

**Comment by orneryd** [comment]
correction:
```
npm install && npm run build && npm run start
```
readme updated
