### ISSUE TITLE
Error while starting npm

### ISSUE THREAD

**Issue by AndreaGot** [timothyswt/big-decks#2]
I am getting this error after install and build:

TypeError: Cannot read property '2' of null
    at saveDeck (C:\Users\AndreaGot\Google Drive\XMage decks\big-decks\lib\save.js:42:45)
    at C:\Users\AndreaGot\Google Drive\XMage decks\big-decks\lib\index.js:36:41
    at mtgtop8 (C:\Users\AndreaGot\Google Drive\XMage decks\big-decks\lib\mtgtop8.js:27:5)
    at C:\Users\AndreaGot\Google Drive\XMage decks\big-decks\lib\index.js:33:40
    at mtgtop8 (C:\Users\AndreaGot\Google Drive\XMage decks\big-decks\lib\mtgtop8.js:27:5)
    at C:\Users\AndreaGot\Google Drive\XMage decks\big-decks\lib\index.js:30:31
    at Array.forEach (<anonymous>)
    at C:\Users\AndreaGot\Google Drive\XMage decks\big-decks\lib\index.js:29:15
    at mtgtop8 (C:\Users\AndreaGot\Google Drive\XMage decks\big-decks\lib\mtgtop8.js:27:5)
    at C:\Users\AndreaGot\Google Drive\XMage decks\big-decks\lib\index.js:24:34
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! big-decks@1.0.0 start: `node lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the big-decks@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AndreaGot\AppData\Roaming\npm-cache\_logs\2018-03-21T10_29_58_204Z-debug.log

**Comment by Simbi0z** [comment]
Same here
